Add Debug Panel for Simulated Data & HighlightedContent Test
ai-cfia/finesse-frontend pull request #20
Opened 2023-09-27 12:57 UTC by CFIALeronB

- Integrated a debug panel to toggle between live and simulated data.
- Source simulated data from `testData.json`.
- Added test for `highlightWords` in `HighlightedContent`, validating highlighted indices for the first data item.

#18

2023-09-27 13:34 UTC, rngadam requested changes

2023-09-27 13:34 UTC, rngadam commented on src/api/useApiUtil.tsx
> +import testData from "../test_data/testData.json"; // Make sure the path points to your test data file
that only works at build time for a specific test data. I want us to have a bit more leeway on what data is returned. Why not make this a text field containing the JSON in the debug panel that we can set with some reasonable default samples?

2023-10-02 13:02 UTC, rngadam approved these changes
Our search results are minimum 10 results. Please open an issue to improve this test data and provide additional samples of query/example results. We'll use this to compare with the actual results to have something to shoot for.

2023-10-30 20:49 UTC, rngadam requested changes

2023-10-30 20:49 UTC, rngadam commented on .github/workflows/pull-request.yml
> -
https://gist.github.com/camh-/1bebfcff1b0f814e9b191edc60d5206b

2023-11-01 21:46 UTC, rngadam approved these changes
LGTM. I'm assuming this is the version before you switched to fetching from finesse-data.

Would suggest you readthrough your code with @RussellJimmies in videoconference so he can make sure nachet-frontend follows some of the same practices.

2023-11-01 21:47 UTC, rngadam requested changes
oops, just saw that the tests are failing, they should be fixed before we merge

2023-11-07 14:13 UTC, rngadam commented
@CFIALeronB tests still failing

2023-11-14 21:07 UTC, CFIALeronB commented
@rngadam tests are now all passing, except the: lint-test / build Expected — Waiting for status to be reported. Not quite sure what needs to be done for that. This status is also present for the other pull requests: #32 , #27, #20

2023-11-15 14:42 UTC, rngadam commented
> @rngadam tests are now all passing, except the: lint-test / build Expected — Waiting for status to be reported. Not quite sure what needs to be done for that. This status is also present for the other pull requests: #32 , #27, #20

@redat97

2023-11-15 15:14 UTC, redat97 commented
Fixed @CFIALeronB @rngadam I think I used the wrong parameter again not sure I fully understand how it works yet since it worked on the other PR I tried it on but looks like I need "lint-test / lint-test" as the source and not "lint-test / build" it's been manually fixed for now but I will document myself on that and fix the script again

2023-11-15 16:12 UTC, rngadam approved these changes

2023-11-17 14:29 UTC, merged