85-update-dockerfile-configuration-to-fix-404
ai-cfia/finesse-frontend pull request #86
Opened 2024-02-28 19:39 UTC by k-allagbe

Closes #85

- [x] serve `dist` instead of `build`
- [x] multi stage dockerfile to reduce container size and potentially build time
- [x] update documentation on how to run the app with docker

2024-02-28 20:00 UTC, SonOfLope approved these changes
I've tested locally and confirm that it works.

2024-03-01 16:03 UTC, rngadam requested changes
please take note of the warnings from the linter also

2024-03-05 20:03 UTC, k-allagbe commented on src/_versions.ts
> +  version: "1.0.0",
Done.

2024-03-06 14:41 UTC, rngadam approved these changes

2024-03-06 15:01 UTC, merged